name: Tweet air quality

on:
  schedule:
    - cron: "33 * * * *"
    - cron: "7 */3 * * *"
  workflow_dispatch:

jobs:
  test-report:
    name: Tweet air quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: air

      - name: mamba list
        shell: bash -l {0}
        run: mamba list

      - name: Maybe set districts env
        if: github.event_name == 'schedule' && github.event.schedule == '7 */3 * * *'
        run: echo DISTRICT_TYPE=SUPERVISORIAL >> $GITHUB_ENV

      - name: Send tweet
        shell: bash -l {0}
        env:
          PURPLEAIR_API_KEY: ${{ secrets.PURPLEAIR_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          jupyter execute purpleair.ipynb
